{% set name = "google-cloud-runtimeconfig" %}
{% set version = "0.31.0" %}
{% set sha256 = "3e0218abc438f2f43605db27189fa7a48c3ca3defc45054dac01835527058a4c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip >=18.1
  run:
    - python >=3.6
    - google-cloud-core >=1.1.0,<2.0.0dev

test:
  imports:
    - google.cloud.client
    - google.cloud.runtimeconfig

about:
  home: https://github.com/googleapis/python-runtimeconfig
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Google Cloud RuntimeConfig API client library
  description: "The Google Cloud RuntimeConfig API enables developers to dynamically configure and expose variables through Google Cloud Platform. In addition, you can also set Watchers and Waiters that will watch for changes to your data and return based on certain conditions.\nSee the [quick start guide](https://googleapis.dev/python/runtimeconfig/latest/index.html#quick-start)."

  doc_url: https://googleapis.dev/python/runtimeconfig/latest/index.html
  dev_url: https://github.com/googleapis/python-runtimeconfig

extra:
  recipe-maintainers:
    - parthea
