{% set name = "google-cloud-runtimeconfig" %}
{% set version = "0.33.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-cloud-runtimeconfig-{{ version }}.tar.gz
  sha256: cc85e5de7cdb58a27561885021ee6fcf1d9f89e0f0db7c371bdca9c54788dd15

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - google-cloud-core >=1.3.0,<3.0.0dev

test:
  imports:
    - google.cloud.client
    - google.cloud.runtimeconfig
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-runtimeconfig
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Google Cloud RuntimeConfig API client library
  description: "The Google Cloud RuntimeConfig API enables developers to dynamically configure and expose variables through Google Cloud Platform. In addition, you can also set Watchers and Waiters that will watch for changes to your data and return based on certain conditions.\nSee the [quick start guide](https://googleapis.dev/python/runtimeconfig/latest/index.html#quick-start)."

  doc_url: https://googleapis.dev/python/runtimeconfig/latest/index.html
  dev_url: https://github.com/googleapis/python-runtimeconfig

extra:
  recipe-maintainers:
    - xylar
    - parthea
